apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::<your-account>:user/<your-user>
      username: github-actions
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::<your-account>:role/<your-node-group-role>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
