{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: 80
      targetPort: {{ $svc.port }}
---
{{- end }}