{{- if and .Values.postgres.enabled (eq .Values.postgres.storageClass "gp2-csi") }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp2
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
{{- end }}
