image:
  repository: your-docker-repo
  tag: latest

services:
  user:
    port: 5001
  product:
    port: 5002
  order:
    port: 5003
  notification:
    port: 5004

# ingress:
#   enabled: true
#   className: nginx
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#   hosts:
#     - host: microservices.local
#       paths:
#         - path: /user
#           service: user
#         - path: /product
#           service: product
#         - path: /order
#           service: order
#         - path: /notification
#           service: notification

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: microservices.local
      paths:
        - path: /user(/|$)(.*)
          pathType: Prefix
          service: user-service
        - path: /product(/|$)(.*)
          pathType: Prefix
          service: product-service
        - path: /order(/|$)(.*)
          pathType: Prefix
          service: order-service
        - path: /notification(/|$)(.*)
          pathType: Prefix
          service: notification-service

env:
  tag: latest
  SECRET_KEY: change-me-secret-key

# ... (existing values remain the same)

postgres:
  enabled: true
  user: "devuser"
  password: "devpass"
  database: "devdb"
  storageSize: "1Gi"
  storageClass: "gp2-csi"  # "gp2" for EKS, "standard" for GKE, or omit for default


