image:
  repository: your-docker-repo
  tag: latest

database:
  secretName: "rds-credentials" # Matches the Terraform-created secret

services:
  user:
    port: 5001
  product:
    port: 5002
  order:
    port: 5003
  notification:
    port: 5004

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: microservices.local
      paths:
        - path: /user
          service: user
        - path: /product
          service: product
        - path: /order
          service: order
        - path: /notification
          service: notification
